### ISSUE TITLE
Is this just a bad fork?

### ISSUE THREAD

**Issue by V-core9** [felix2056/muzbnb#21]
https://github.com/WPSHOPLA/MuzBNB_Laravel 
This seems to be the original project that was manually uploaded here...instead of forking or something.

**Comment by felix2056** [comment]
Unrelated. That was the initial and incomplete project, mostly just a fresh copy of Laravel installation.

This repository ([felix2056](https://github.com/felix2056) [muzbnb](https://github.com/felix2056/muzbnb)) is the current MuzBNB owned by Hadi and built by me in 2020 which has long since been discontinued due to lack of funding.
https://www.producthunt.com/products/muzbnb

**Comment by V-core9** [comment]
Not so sure it's unrelated since the mentioned repository is public and 3years older than this one.
Plus it contains mostly the same code (except the additions that were added).

**Comment by felix2056** [comment]
Re-read this last bit.

> This repository ([felix2056](https://github.com/felix2056) [muzbnb](https://github.com/felix2056/muzbnb)) is the current MuzBNB owned by Hadi and built by me in 2020 which has long since been discontinued due to lack of funding.
